package com.erika.vsanalogwarfare.vehiclesetup;

public enum VehicleSetupActionType {
    PLACE_BLOCK,
    REMOVE_BLOCK,
    LINK_DBW_BACKUPS,
    CREATE_TWEAKED_CONTROLLER,
    SET_TRACKWORK_STIFFNESS,
    SPAWN_TALLYHO_HULL_MG,
    SPAWN_TALLYHO_ENTITY,
    GENERIC_BLOCK_INTERACTION,
    GENERIC_BLOCK_LEFT_CLICK,
    CONFIGURE_ENDER_TRANSMITTER
}
