modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0"

[[mods]]
modId="vs_analog_warfare"
version="0.4.2-vs2.3"
displayName="VS Analog Warfare"
authors="Erika"
description='''Minimal Valkyrien Skies/Create Big Cannons compatible analog optics prototype.'''

[[mixins]]
config="vs_analog_warfare.mixins.json"

[[mixins]]
config="vs_analog_warfare.compat.mixins.json"

[[dependencies.vs_analog_warfare]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.vs_analog_warfare]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.vs_analog_warfare]]
modId="valkyrienskies"
mandatory=true
versionRange="[2.3.0-beta.5,2.4.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.vs_analog_warfare]]
modId="create"
mandatory=true
versionRange="[0.5.1.j,0.6.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.vs_analog_warfare]]
modId="createbigcannons"
mandatory=true
versionRange="[5.8.2,5.9.0)"
ordering="AFTER"
side="BOTH"
